- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    region: us-east-1
    keypair: cloudformation-key 
    stack_name: xrv9k-ha-test
     
  tasks:
    - name: try creating a key pair with name of an already existing keypair
      amazon.aws.ec2_key:
        name: cloudformation-key 
        key_material: "{{ lookup('file', '/root/ssh/id_rsa.pub') }}"
        force: true


    - name: Delete any previously existing xrv9k HA stack
      cloudformation:
        stack_name: "{{ stack_name }}"
        region: "{{ region }}"
        state: absent 
        template: "{{ playbook_dir }}/cloudformation/xrv9k_aws_ha_topo_basic.yml"
        tags:
          stack: "{{ stack_name }}"

